redmine_dir: /var/lib/redmine
redmine_compose_src: "{{ playbook_dir }}/../redmine/docker-compose.yml"
redmine_files_src: "{{ playbook_dir }}/../redmine/"
env_data: "{{ playbook_dir }}/../../infra-vars/tasks/"