# modifiez le chemin d'acces et nom de votre cle avant d'executer
ansible_user: appadmin
ansible_port: 4242
# (proxy/manager/workersâ€¦)
ansible_ssh_private_key_file: ~/.ssh/id_ed25519_bastion
ansible_ssh_common_args: >
  -o StrictHostKeyChecking=no
  -o ProxyCommand="ssh -i {{ ansible_ssh_private_key_file }} -W %h:%p -q bastion@{{ hostvars["bastion"].ansible_host }} -p 4242"
