# modifiez le chemin d'acces et nom de votre cle avant d'executer
ansible_user: appadmin
ansible_port: 4242
# (proxy/manager/workersâ€¦)
ansible_ssh_private_key_file: ~/.ssh/ssh-redmine

ansible_ssh_common_args: >
  -o StrictHostKeyChecking=no
  -o ProxyCommand="ssh -i ~/.ssh/ssh-redmine -p 4242 -W %h:%p bastion@{{ hostvars['bastion'].ansible_host }}"