---
- name: Créer le répertoire de déploiement
  file:
    path: "{{ redmine_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copier le fichier docker-compose.yml commun du projet
  copy:
    src: "{{ redmine_compose_src }}"
    dest: "{{ redmine_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
  notify: Restart redmine stack

- name: Copier les fichiers nécessaires (Dockerfile, entrypoint, etc.)
  copy:
    src: "{{ redmine_files_src }}/"
    dest: "{{ redmine_dir }}/"
    owner: root
    group: root
    mode: '0644'
    
#- name: suppression des fichiers
#  file:
#    path: "{{ redmine_dir }}/{{ item }}"
#    state: absent
#    loop:
#      - ".git"
#      - "readme"
#      - "README.md"
#      - "docker-compose.yml"
#    ignore_errors: yes

- name: Créer les secrets Docker Swarm à partir des sorties Terraform
  shell: |
    for secret in REDMINE_DB_POSTGRES REDMINE_DB_PORT REDMINE_DB_USERNAME REDMINE_DB_PASSWORD REDMINE_DB_DATABASE REDMINE_DB_ENCODING REDMINE_SECRET_KEY_BASE; do
      if ! docker secret ls --format '{{"{{.Name}}"}}' | grep -q "^$secret$"; then
        case "$secret" in
          REDMINE_DB_POSTGRES)
            echo "{{ env_data.env.REDMINE_DB_POSTGRES }}" | docker secret create $secret -
            ;;
          REDMINE_DB_PORT)
            echo "{{ env_data.env.REDMINE_DB_PORT.value | default('5432') }}" | docker secret create $secret -
            ;;
          REDMINE_DB_USERNAME)
            echo "{{ env_data.env.REDMINE_DB_USERNAME }}" | docker secret create $secret -
            ;;
          REDMINE_DB_PASSWORD)
            echo "{{ env_data.env.REDMINE_DB_PASSWORD }}" | docker secret create $secret -
            ;;
          REDMINE_DB_DATABASE)
            echo "{{ env_data.env.REDMINE_DB_DATABASE.value | default('redmine') }}" | docker secret create $secret -
            ;;
          REDMINE_DB_ENCODING)
            echo "{{ env_data.env.REDMINE_DB_ENCODING | default('utf8') }}" | docker secret create $secret -
            ;;
          REDMINE_SECRET_KEY_BASE)
            openssl rand -hex 64 | docker secret create $secret -
            ;;
        esac
      fi
    done
  args:
    executable: /bin/bash
  no_log: true


- name: Déployer ou redéployer le stack Redmine avec Docker Swarm
  shell: docker stack deploy -c {{ redmine_dir }}/docker-compose.yml redmine
  args:
    chdir: "{{ redmine_dir }}"
  register: redmine_deploy

- name: Vérifier le statut du stack
  shell: docker stack ps redmine --format '{{"{{.Name}}\t{{.CurrentState}}"}}'
  register: redmine_status
  changed_when: false

- name: Afficher le statut des services Redmine
  debug:
    var: redmine_status.stdout_lines

- name: Vérifier la disponibilité du service Redmine
  uri:
    url: "http://{{ terraform_outputs.proxy_ip.value }}:3000"
    method: GET
    status_code: 200
  register: redmine_health
  retries: 10
  delay: 10
  until: redmine_health.status == 200
  changed_when: false

